import { Inter } from "next/font/google";
import "./globals.css";
import "antd/dist/reset.css";
import Head from 'next/head';
import Footer from './components/footer/Footer';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "SkyMap",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        
      </Head>
      <body className={inter.className}>
        <div className="main-content">
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
