'use client';

import Head from 'next/head';
import { useRef } from 'react';
import FlightDetails from './components/flightDetails/FlightDetails';
import Header from './components/header/Header';
import styles from './page.module.css';
import AviationTrends from './components/aviationTrends/AviationTrends';

export default function Home() {
  const flight = {
    departure: 'Tbilisi (TB)',
    arrival: 'Amsterdam (NL)',
    number: 'BT 618',
    airline: 'Air Canada',
    status: 'On time',
    duration: '4',
    departureTime: '6:15 PM 22/10/2024',
    arrivalTime: '8:15 PM 22/10/2024',
  };

  const posts = [
    {
      title: 'Georgian Airways News',
      description: 'Latest updates and news from Georgian Airways.',
      date: 'June 25, 2024',
      link: '#',
      image: '/images/georgianAirways.jpg', 
    },
    {
      title: 'Lufthansa Safety Measures',
      description: 'Safety measures implemented by Lufthansa.',
      date: 'June 20, 2024',
      link: '#',
      image: '/images/lufthansa.jpg', 
    },
    
  ];

  const flightDetailsRef = useRef();

  const handleLogoClick = () => {
    if (flightDetailsRef.current) {
      flightDetailsRef.current.resetState();
    }
  };

  return (
    <div className={styles.backgroundWrapper}>
      <Head>
        <title>SkyMap</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header onLogoClick={handleLogoClick} />
      <div className={styles.contentWrapper}>
        <div className={styles.headerContainer}>
          <div className={styles.headerText}>
            <h1 className={styles.headerTitle}>SkyMap</h1>
            <p className={styles.headerSubtitle}>
              Track your flight, accurate, actionable data and insights that inform every aviation decision.
            </p>
          </div>
          <div className={styles.flightDetailsContainer}>
            <FlightDetails ref={flightDetailsRef} />
          </div>
        </div>
        
        <AviationTrends />

        <div className={styles.scrollContainer}>
          <div className={`${styles.blogContainer} ${styles.hidden}`}>
            {posts.map((post, index) => (
              <div key={index} className={styles.blogPost}>
                <img src={post.image} alt={post.title} className={styles.blogImage} />
                <h2>{post.title}</h2>
                <p>{post.description}</p>
                <p>{post.date}</p>
                <a href={post.link}>Read More</a>
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}
