const jobsData = [
    {
      id: 1,
      title: "Test Equipment Engineer (Onsite)",
      location: "Georgia, Tbilisi",
      jobID: "01712599",
      category: "Engineering",
      type: "Full Time",
      datePosted: "2024-07-08",
      businessUnit: "Georgian Airways",
      country: "Georgia",
      city: "Tbilisi",
      locationType: "Onsite",
      applyUrl: "#",
    },
    {
      id: 2,
      title: "Senior Quality Engineer",
      location: "Hungary, Budapest",
      jobID: "017269266",
      category: "Engineering",
      type: "Full Time",
      datePosted: "2024-05-16",
      businessUnit: "WizzAir",
      country: "Hungary",
      city: "Budapest",
      locationType: "Onsite",
      applyUrl: "#",
    },
    {
      id: 3,
      title: "Backend Developer",
      location: "Netherlands, Amsterdam",
      jobID: "01712593",
      category: "Java Developer",
      type: "Part Time",
      datePosted: "2024-06-12",
      businessUnit: "TransAvia",
      country: "Netherlands",
      city: "Amsterdam",
      locationType: "Onsite",
      applyUrl: "#",
    },
    {
      id: 4,
      title: "Full-Stack Developer",
      location: "Netherlands, Utrecht",
      jobID: "01712594",
      category: "Full-Stack Developer",
      type: "Full Time",
      datePosted: "2024-06-13",
      businessUnit: "TransAvia",
      country: "Netherlands",
      city: "Utrecht",
      locationType: "Remote",
      applyUrl: "#",
    },
    {
      id: 5,
      title: "Front-End Developer",
      location: "Netherlands, Maastricht",
      jobID: "01712595",
      category: "Front-End Developer",
      type: "Part Time",
      datePosted: "2024-06-14",
      businessUnit: "TransAvia",
      country: "Netherlands",
      city: "Maastricht",
      locationType: "Hybrid",
      applyUrl: "#",
    },
    {
      id: 6,
      title: "Software Engineer",
      location: "Hungary, Debrecen",
      jobID: "01712596",
      category: "Engineering",
      type: "Full Time",
      datePosted: "2024-06-15",
      businessUnit: "WizzAir",
      country: "Hungary",
      city: "Debrecen",
      locationType: "Remote",
      applyUrl: "#",
    },
    {
      id: 7,
      title: "Project Manager",
      location: "Georgia, Batumi",
      jobID: "01712597",
      category: "Engineering",
      type: "Full Time",
      datePosted: "2024-06-16",
      businessUnit: "Georgian Airways",
      country: "Georgia",
      city: "Batumi",
      locationType: "Onsite",
      applyUrl: "#",
    },
    {
      id: 8,
      title: "Data Scientist",
      location: "Netherlands, Eindhoven",
      jobID: "01712598",
      category: "Engineering",
      type: "Part Time",
      datePosted: "2024-06-17",
      businessUnit: "TransAvia",
      country: "Netherlands",
      city: "Eindhoven",
      locationType: "Hybrid",
      applyUrl: "#",
    },
    {
      id: 9,
      title: "Quality Assurance Engineer",
      location: "Hungary, Budapest",
      jobID: "01712599",
      category: "Engineering",
      type: "Full Time",
      datePosted: "2024-06-18",
      businessUnit: "WizzAir",
      country: "Hungary",
      city: "Budapest",
      locationType: "Onsite",
      applyUrl: "#",
    },
    {
      id: 10,
      title: "System Architect",
      location: "Georgia, Tbilisi",
      jobID: "01712600",
      category: "Engineering",
      type: "Full Time",
      datePosted: "2024-06-19",
      businessUnit: "Georgian Airways",
      country: "Georgia",
      city: "Tbilisi",
      locationType: "Remote",
      applyUrl: "#",
    },
    {
      id: 11,
      title: "Cloud Engineer",
      location: "Netherlands, Amsterdam",
      jobID: "01712601",
      category: "Engineering",
      type: "Part Time",
      datePosted: "2024-06-20",
      businessUnit: "TransAvia",
      country: "Netherlands",
      city: "Amsterdam",
      locationType: "Hybrid",
      applyUrl: "#",
    },
    {
      id: 12,
      title: "Network Engineer",
      location: "Hungary, Debrecen",
      jobID: "01712602",
      category: "Engineering",
      type: "Full Time",
      datePosted: "2024-06-21",
      businessUnit: "WizzAir",
      country: "Hungary",
      city: "Debrecen",
      locationType: "Onsite",
      applyUrl: "#",
    },
    {
      id: 13,
      title: "Machine Learning Engineer",
      location: "Netherlands, Utrecht",
      jobID: "01712603",
      category: "Engineering",
      type: "Full Time",
      datePosted: "2024-06-22",
      businessUnit: "TransAvia",
      country: "Netherlands",
      city: "Utrecht",
      locationType: "Remote",
      applyUrl: "#",
    },
    {
      id: 14,
      title: "DevOps Engineer",
      location: "Georgia, Batumi",
      jobID: "01712604",
      category: "Engineering",
      type: "Full Time",
      datePosted: "2024-06-23",
      businessUnit: "Georgian Airways",
      country: "Georgia",
      city: "Batumi",
      locationType: "Onsite",
      applyUrl: "#",
    },
    {
      id: 15,
      title: "Cybersecurity Analyst",
      location: "Hungary, Budapest",
      jobID: "01712605",
      category: "Engineering",
      type: "Part Time",
      datePosted: "2024-06-24",
      businessUnit: "WizzAir",
      country: "Hungary",
      city: "Budapest",
      locationType: "Hybrid",
      applyUrl: "#",
    },
    {
      id: 16,
      title: "Frontend Developer",
      location: "Netherlands, Maastricht",
      jobID: "01712606",
      category: "Front-End Developer",
      type: "Full Time",
      datePosted: "2024-06-25",
      businessUnit: "TransAvia",
      country: "Netherlands",
      city: "Maastricht",
      locationType: "Remote",
      applyUrl: "#",
    },
    {
      id: 17,
      title: "Full Stack Developer",
      location: "Hungary, Debrecen",
      jobID: "01712607",
      category: "Full-Stack Developer",
      type: "Full Time",
      datePosted: "2024-06-26",
      businessUnit: "WizzAir",
      country: "Hungary",
      city: "Debrecen",
      locationType: "Onsite",
      applyUrl: "#",
    },
    {
      id: 18,
      title: "Java Developer",
      location: "Netherlands, Eindhoven",
      jobID: "01712608",
      category: "Java Developer",
      type: "Part Time",
      datePosted: "2024-06-27",
      businessUnit: "TransAvia",
      country: "Netherlands",
      city: "Eindhoven",
      locationType: "Hybrid",
      applyUrl: "#",
    },
    {
      id: 19,
      title: "Software Architect",
      location: "Georgia, Tbilisi",
      jobID: "01712609",
      category: "Engineering",
      type: "Full Time",
      datePosted: "2024-06-28",
      businessUnit: "Georgian Airways",
      country: "Georgia",
      city: "Tbilisi",
      locationType: "Remote",
      applyUrl: "#",
    },
    {
      id: 20,
      title: "Product Manager",
      location: "Netherlands, Amsterdam",
      jobID: "01712610",
      category: "Engineering",
      type: "Part Time",
      datePosted: "2024-06-29",
      businessUnit: "TransAvia",
      country: "Netherlands",
      city: "Amsterdam",
      locationType: "Onsite",
      applyUrl: "#",
    },
    {
      id: 21,
      title: "System Administrator",
      location: "Hungary, Budapest",
      jobID: "01712611",
      category: "Engineering",
      type: "Full Time",
      datePosted: "2024-06-30",
      businessUnit: "WizzAir",
      country: "Hungary",
      city: "Budapest",
      locationType: "Remote",
      applyUrl: "#",
    },
    {
      id: 22,
      title: "Data Analyst",
      location: "Netherlands, Utrecht",
      jobID: "01712612",
      category: "Engineering",
      type: "Full Time",
      datePosted: "2024-07-01",
      businessUnit: "TransAvia",
      country: "Netherlands",
      city: "Utrecht",
      locationType: "Onsite",
      applyUrl: "#",
    },
    {
      id: 23,
      title: "Network Architect",
      location: "Hungary, Debrecen",
      jobID: "01712613",
      category: "Engineering",
      type: "Part Time",
      datePosted: "2024-07-02",
      businessUnit: "WizzAir",
      country: "Hungary",
      city: "Debrecen",
      locationType: "Hybrid",
      applyUrl: "#",
    },
    {
      id: 24,
      title: "Machine Learning Scientist",
      location: "Netherlands, Maastricht",
      jobID: "01712614",
      category: "Engineering",
      type: "Full Time",
      datePosted: "2024-07-03",
      businessUnit: "TransAvia",
      country: "Netherlands",
      city: "Maastricht",
      locationType: "Remote",
      applyUrl: "#",
    },
    {
      id: 25,
      title: "UI/UX Designer",
      location: "Georgia, Tbilisi",
      jobID: "01712615",
      category: "Engineering",
      type: "Full Time",
      datePosted: "2024-07-04",
      businessUnit: "Georgian Airways",
      country: "Georgia",
      city: "Tbilisi",
      locationType: "Onsite",
      applyUrl: "#",
    },
    {
      id: 26,
      title: "DevOps Specialist",
      location: "Netherlands, Eindhoven",
      jobID: "01712616",
      category: "Engineering",
      type: "Part Time",
      datePosted: "2024-07-05",
      businessUnit: "TransAvia",
      country: "Netherlands",
      city: "Eindhoven",
      locationType: "Hybrid",
      applyUrl: "#",
    },
    {
      id: 27,
      title: "Software Tester",
      location: "Hungary, Budapest",
      jobID: "01712617",
      category: "Engineering",
      type: "Full Time",
      datePosted: "2024-07-06",
      businessUnit: "WizzAir",
      country: "Hungary",
      city: "Budapest",
      locationType: "Remote",
      applyUrl: "#",
    },
    {
      id: 28,
      title: "IT Support Specialist",
      location: "Georgia, Batumi",
      jobID: "01712618",
      category: "Engineering",
      type: "Full Time",
      datePosted: "2024-07-07",
      businessUnit: "Georgian Airways",
      country: "Georgia",
      city: "Batumi",
      locationType: "Onsite",
      applyUrl: "#",
    },
    {
      id: 29,
      title: "Security Engineer",
      location: "Netherlands, Utrecht",
      jobID: "01712619",
      category: "Engineering",
      type: "Part Time",
      datePosted: "2024-07-08",
      businessUnit: "TransAvia",
      country: "Netherlands",
      city: "Utrecht",
      locationType: "Hybrid",
      applyUrl: "#",
    },
    {
      id: 30,
      title: "Database Administrator",
      location: "Hungary, Debrecen",
      jobID: "01712620",
      category: "Engineering",
      type: "Full Time",
      datePosted: "2024-07-09",
      businessUnit: "WizzAir",
      country: "Hungary",
      city: "Debrecen",
      locationType: "Remote",
      applyUrl: "#",
    },
    {
      id: 31,
      title: "Solutions Architect",
      location: "Netherlands, Amsterdam",
      jobID: "01712621",
      category: "Engineering",
      type: "Part Time",
      datePosted: "2024-07-10",
      businessUnit: "TransAvia",
      country: "Netherlands",
      city: "Amsterdam",
      locationType: "Onsite",
      applyUrl: "#",
    }
  ];
  
  export default jobsData;
  